// <auto-generated />
using System;
using Dessalement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dessalement.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240509214812_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dessalement.Models.Usager", b =>
                {
                    b.Property<string>("typeusage")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("codeusage")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("datenaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fixe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lieunaissance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("portable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("propriétaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("superficiesouscrite")
                        .HasColumnType("real");

                    b.HasKey("typeusage", "codeusage");

                    b.ToTable("usagers");
                });
#pragma warning restore 612, 618
        }
    }
}
